### ISSUE TITLE
What is this project about?

### ISSUE THREAD

**Issue by guettli** [sergei-maertens/django-ponyjs#1]
> A Javascript framework for Django!

I am interested, but ... some sentences about the goal of this project would be nice :-)

**Comment by sergei-maertens** [comment]
Hi, cool that you're interested!

The `develop` version of the docs should address your question: http://django-ponyjs.readthedocs.org/en/develop/

This project is still very much work-in-progress, features are incomplete or completely missing, so it's definitely not production ready.

If, however, you want to see some use cases, I'm developing this library as I need features for another project. Example usages:
- ORM like REST Api: https://github.com/modelbrouwers/modelbrouwers/blob/0d776632057185a1c28d5f3017e7e461fa942dec/src/brouwers/kits/static/kits/js/modelkit.widget.js#L201
- Formsets: https://github.com/modelbrouwers/modelbrouwers/blob/0d776632057185a1c28d5f3017e7e461fa942dec/src/brouwers/builds/static/builds/js/builds.js#L125

**Comment by sergei-maertens** [comment]
@guettli any more remarks, otherwise I'll consider my answer sufficient and close this issue

**Comment by guettli** [comment]
Yes, thank you. I close it.
